apiVersion: v1
kind: Service
metadata:
    name: "sysdigcl1-4026"
    labels:
        app: "sysdigcl1-4026"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "sysdigcl1-4026"